application:
  app:
    host: "${APP_HOST:http://localhost}"
    name: "${APP_NAME:TeamManager}"
    port: "${APP_PORT:8080}"
server:
  port: "${APP_PORT:8080}"
app:
  name: "${APP_NAME:TeamManager}"
springdoc:
  show-actuator: false
  writer-with-default-pretty-printer: true
  pre-loading-enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
error:
  handling:
    exception-logging: with_stacktrace
    http-status-in-json-response: true
spring:
  application:
    name: TeamManager

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/myDB
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3NDExMjY1MTMsImV4cCI6MTc3MjY2MjUxMywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IlRoZW8iLCJTdXJuYW1lIjoiVGhldGhlNDQiLCJFbWFpbCI6Im1vdXNuaWVydC5wcm9AZ21haWwuY29tIiwiUm9sZSI6IkFETUlOIn0.x1ved56eUs_LhpafnC47LRJkCuPAGktwoUF4tBgm9hg
logging:
  level:
    org:
      springframework:
        security: DEBUG